# Generated by Django 2.2.6 on 2019-10-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
